name: E:/git/ohdsi-studies/Glp1DiliStudyRepoTemplate/renv/python/condaenvs/renv-python
channels:
  - conda-forge
  - defaults
dependencies:
  - atk=2.36.0=h2eaa2aa_0
  - atk-1.0=2.36.0=hd78058f_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=h59b6b97_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.8.30=h56e8100_0
  - cairo=1.16.0=haedb8bc_5
  - clang_variant=1.0=default
  - clangdev=5.0.0=h5aa907a_1012
  - expat=2.6.3=h5da7b33_0
  - fftw=3.3.9=h2bbff1b_2
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hb33846d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=ha860e81_0
  - fribidi=1.0.10=h62dcd97_0
  - gdk-pixbuf=2.42.10=h827c3e9_1
  - getopt-win32=0.1=h2bbff1b_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - gobject-introspection=1.72.0=py37he924643_1
  - graphite2=1.3.14=hd77b12b_1
  - graphviz=2.50.0=h7eca76f_1
  - gts=0.7.6=h63ab5a1_3
  - harfbuzz=4.3.0=hb646838_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - intel-openmp=2021.4.0=haa95532_3556
  - joblib=1.1.1=py37haa95532_0
  - jpeg=9e=h827c3e9_3
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.9.0=12_win64_mkl
  - libboost=1.82.0=h3399ecb_2
  - libcblas=3.9.0=12_win64_mkl
  - libcurl=8.9.1=h0416ee5_0
  - libcxx=7.0.0=h1ad3211_1002
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libflang=5.0.0=h6538335_20180525
  - libgd=2.3.3=hd77b12b_3
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - liblapack=3.9.0=12_win64_mkl
  - libopenblas=0.3.28=pthreads_hf0a32cb_0
  - libpng=1.6.39=h8cc25b3_0
  - libsqlite=3.46.1=h2466b09_0
  - libssh2=1.11.0=h291bd65_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.13.1=h24da03e_2
  - libzlib=1.2.13=h2466b09_6
  - llvm-meta=7.0.0=0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2021.4.0=h0e2418a_729
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - numpy=1.21.5=py37h7a0a035_3
  - numpy-base=1.21.5=py37hca35cd5_3
  - openjpeg=2.5.2=hae555c5_0
  - openmp=5.0.0=vc14_0
  - openssl=3.3.2=h2466b09_0
  - pango=1.50.7=h78c2152_0
  - pcre2=10.42=h0ff8eda_1
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.40.0=h2bbff1b_1
  - poppler=22.12.0=h0bf3bde_3
  - poppler-data=0.4.11=haa95532_1
  - pydotplus=2.0.2=py_3
  - pyparsing=3.0.9=py37haa95532_0
  - python=3.7.12=h900ac77_100_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.7=4_cp37m
  - pytz=2022.7=py37haa95532_0
  - scikit-learn=1.0.2=py37hf11a4ad_1
  - scipy=1.7.3=py37h7a0a035_2
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - sklearn-json=0.1.0=pyhd8ed1ab_0
  - sqlite=3.46.1=h2466b09_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.14=h0416ee5_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=h8a93ad2_21
  - vc14_runtime=14.40.33810=ha82c5b3_21
  - vs2015_runtime=14.40.33810=h3bf8584_21
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.5=hd43e919_2
prefix: E:/git/ohdsi-studies/Glp1DiliStudyRepoTemplate/renv/python/condaenvs/renv-python
